"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-01 16:55:45.265984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('default_currency', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('notify_new_objects', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'code', name='uq_agents_agency_code')
    )
    op.create_index(op.f('ix_agents_agency_id'), 'agents', ['agency_id'], unique=False)
    op.create_table('dictionaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'category', 'value', name='uq_dictionaries_agency_cat_value')
    )
    op.create_index(op.f('ix_dictionaries_agency_id'), 'dictionaries', ['agency_id'], unique=False)
    op.create_index(op.f('ix_dictionaries_category'), 'dictionaries', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('agency_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('apartments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_phone', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('furniture_appliances', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('source_link', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'display_id', name='uq_apartments_agency_display')
    )
    op.create_index('ix_apartments_agency_created', 'apartments', ['agency_id', 'created_at'], unique=False)
    op.create_index('ix_apartments_agency_district', 'apartments', ['agency_id', 'district'], unique=False)
    op.create_index(op.f('ix_apartments_agency_id'), 'apartments', ['agency_id'], unique=False)
    op.create_index('ix_apartments_agency_price', 'apartments', ['agency_id', 'price'], unique=False)
    op.create_index('ix_apartments_agency_rooms', 'apartments', ['agency_id', 'rooms'], unique=False)
    op.create_index('ix_apartments_agency_status', 'apartments', ['agency_id', 'status'], unique=False)
    op.create_index('ix_apartments_agency_type', 'apartments', ['agency_id', 'type'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_agency_id'), 'invites', ['agency_id'], unique=False)
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_table('apartment_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('apartment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_events_agency_id'), 'apartment_events', ['agency_id'], unique=False)
    op.create_index('ix_apartment_events_apartment', 'apartment_events', ['agency_id', 'apartment_id'], unique=False)
    op.create_table('apartment_photos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('apartment_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_photos_agency_id'), 'apartment_photos', ['agency_id'], unique=False)
    op.create_index('ix_apartment_photos_apartment', 'apartment_photos', ['agency_id', 'apartment_id'], unique=False)
    op.create_index(op.f('ix_apartment_photos_storage_key'), 'apartment_photos', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apartment_photos_storage_key'), table_name='apartment_photos')
    op.drop_index('ix_apartment_photos_apartment', table_name='apartment_photos')
    op.drop_index(op.f('ix_apartment_photos_agency_id'), table_name='apartment_photos')
    op.drop_table('apartment_photos')
    op.drop_index('ix_apartment_events_apartment', table_name='apartment_events')
    op.drop_index(op.f('ix_apartment_events_agency_id'), table_name='apartment_events')
    op.drop_table('apartment_events')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_index(op.f('ix_invites_agency_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index('ix_apartments_agency_type', table_name='apartments')
    op.drop_index('ix_apartments_agency_status', table_name='apartments')
    op.drop_index('ix_apartments_agency_rooms', table_name='apartments')
    op.drop_index('ix_apartments_agency_price', table_name='apartments')
    op.drop_index(op.f('ix_apartments_agency_id'), table_name='apartments')
    op.drop_index('ix_apartments_agency_district', table_name='apartments')
    op.drop_index('ix_apartments_agency_created', table_name='apartments')
    op.drop_table('apartments')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dictionaries_category'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_agency_id'), table_name='dictionaries')
    op.drop_table('dictionaries')
    op.drop_index(op.f('ix_agents_agency_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agencies')
    # ### end Alembic commands ###
